apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: simple-app
  namespace: simple-app
spec:
  selector:
    matchExpressions:
    - key: name  
      operator: In
      values:
      - simple-app
  componentKinds:
  - group: app.ibm.com/v1alpha1
    kind: Subscription
