apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: simple-app                          
  namespace: simple-app
  labels:
    name: simple-app
  annotations:
    apps.open-cluster-management.io/github-branch: main
    apps.open-cluster-management.io/github-path: app
spec:
  channel:  simple-app/simple-app-channel
  placement: 
    placementRef: 
      kind: PlacementRule
      name: simple-app-placement
